### ISSUE TITLE
Unexpectedly lazy function

### ISSUE THREAD

**Issue by chr15m** [retrogradeorbit/bootleg#3]
Not sure if this is a bug or not.

Same files as previous issue.

```clojure
(mustache "index.template.html" {:content (markdown "README.md")})
```

Yields:

```html
      <section id="content">clojure.lang.LazySeq@7f4072bd45d0</section>
```

It appears sci has no `doall`.

**Comment by retrogradeorbit** [comment]
Use `(markdown "README.html" :html)`

`markdown` has a default return type of `:hiccup-seq`

**Comment by chr15m** [comment]
@retrogradeorbit yep that works, thanks. Might be an idea to add some documentation on this, like common gotchas. For example somebody searching for "bootleg LazySeq" would want to find that.
