### ISSUE TITLE
<header> tags inside loaded markup stay munged

### ISSUE THREAD

**Issue by retrogradeorbit** [retrogradeorbit/bootleg#31]
```
      <!-- Header -->
      <head-bootleg-mungeder id="header">
        <img alt="" src="images/logo.png">
        <h1 id="logo">
          <a href="/">EPIC CASTLE</a>
        </h1>
      </head-bootleg-mungeder>
```

**Comment by chr15m** [comment]
Just ran into this one was about to file an issue.

**Comment by chr15m** [comment]
Any way I can work around this?

**Comment by retrogradeorbit** [comment]
@chr15m its fixed in develop branch. You can build it yourself `make clean all`. Or use my snapshot build from here: https://epiccastle.io/bootleg/bootleg-0.1.6-SNAPSHOT-linux-amd64.tgz
