### ISSUE TITLE
YAML upgrade to SnakeYAML 2.0

### ISSUE THREAD

**Issue by cloojure** [retrogradeorbit/bootleg#46]
Hi  -  I also had a problem with the stale io.forward/yaml and this issue: 

    https://github.com/owainlewis/yaml/issues/28

So, I wrote my own YAML wrapper to SnakeYAML 2.0.  You can see it here:  

    https://github.com/cloojure/tupelo/blob/master/src/clj/tupelo/parse/yaml.clj

Feel free to either reference this or copy it into your own lib.

Alan

**Comment by retrogradeorbit** [comment]
Fixed in v0.1.8
