### ISSUE TITLE
add clj-time

### ISSUE THREAD

**Issue by retrogradeorbit** [retrogradeorbit/bootleg#51]

**Comment by borkdude** [comment]
Note that by some clj-time is considered deprecated since joda-time is also considered deprecated now that we have java.time. In babashka I've chosen to just add all of the java.time classes so people can just use those as they see fit (e.g. build a small library on top of that). Just my 2 cts.

**Comment by retrogradeorbit** [comment]
@borkdude good idea. I didn't realise about the deprecation for java.time. I will start investigating java.time. Thanks for the tip!

**Comment by retrogradeorbit** [comment]
```
$ bootleg -d -e '(import [java.time LocalDate]) (LocalDate/now)'
#object[java.time.LocalDate "0x7d108063" "2020-01-28"]
```
