### ISSUE TITLE
xml conversion not working in native-image binary

### ISSUE THREAD

**Issue by retrogradeorbit** [retrogradeorbit/bootleg#56]
```
$ bootleg -d -e '(convert-to [:link "foo"] :xml)'
bootleg: script error at line , column : Factory configuration error: Provider com.sun.xml.internal.stream.XMLOutputFactoryImpl not found
```

```
$ lein run -- -d -e '(convert-to [:link "foo"] :xml)'
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><link>foo</link>"
```

Another reflection error?

**Comment by borkdude** [comment]
Also see https://github.com/borkdude/babashka/issues/153

**Comment by retrogradeorbit** [comment]
@borkdude ah thanks! Just guessed at the reflection config and it worked.

As an aside, I had to use the `[org.clojure/data.xml "0.2.0-alpha6"]` version, and then pass through the associated meta data to get xml namespaces working (so you can parse xml docs with namespaces, convert to hiccup, then back out and preserve the namespaces). xml parsing functionality is not exposed in bootleg yet as there are still some minor issues and unsupported hiccup functionality, but might help you integrate it into bb.

https://github.com/retrogradeorbit/bootleg/blob/master/src/bootleg/utils.clj#L307-L330

**Comment by retrogradeorbit** [comment]
I do plan on more complete xml support to come...

**Comment by retrogradeorbit** [comment]
Uploaded new build to release page.
