### ISSUE TITLE
Can we have the ns/require code from spire in bootleg?

### ISSUE THREAD

**Issue by chr15m** [retrogradeorbit/bootleg#58]
:pray:

**Comment by chr15m** [comment]
Oh, there's already `load-file`: https://github.com/retrogradeorbit/bootleg/blob/ebe7748a3afc79f86e57055a7e134d02e59c759a/examples/hiccup/base.clj#L11

**Comment by retrogradeorbit** [comment]
Fixed in v0.1.8
