### ISSUE TITLE
Quickstart example should walk you through one of the examples

### ISSUE THREAD

**Issue by chr15m** [retrogradeorbit/bootleg#6]
A beginner coming to this for the first time and seeing the "quickstart" examples with `-e` will probably get confused. What I want to see as a new user is basically the contents of `examples/quickstart` and the clojure code that would be required to render that into a site. I'd want this in a conversational tone like:

### Quickstart

Imagine you have an HTML template like this:

```html
<bod>...some valid code here...</body>
```

You want to merge that with a JSON file like this: 

...

Then you want to include some Markdown from a file called README.md which looks like this:

...

And so on.

**Comment by retrogradeorbit** [comment]
I think this should not be quickstart. I was going to include a section further down called "Examples" with lots of more indepth examples. 

Quickstart is for copy-paste... yes I get the same result... I will read further imho.

**Comment by retrogradeorbit** [comment]
Rewrote the quickstart to use files instead of -e evaluations. Reads much better now.

**Comment by chr15m** [comment]
Agree, LGTM!
