### ISSUE TITLE
add babashka pod support

### ISSUE THREAD

**Issue by retrogradeorbit** [retrogradeorbit/bootleg#60]

**Comment by martinklepsch** [comment]
I'm currently rebuilding my blog using babashka and bootleg and being able to call bootleg stuff from within babashka would be super nice. 👍

**Comment by retrogradeorbit** [comment]
Fixed in v0.1.8

**Comment by martinklepsch** [comment]
Just wanted to say that this is super amazing and makes it such a joy to work with bootleg! ❤️
