### ISSUE TITLE
Startup performance suggestions

### ISSUE THREAD

**Issue by borkdude** [retrogradeorbit/bootleg#65]
It currenly takes around 120ms on my Macbook Pro 2019 to `load-pod` bootleg. Which is pretty good, but maybe there are some ways to improve on it.

``` clojure
(ns mybbscript
  (:require [babashka.pods :as pods]))

(println "loading pod")
(time (pods/load-pod "bootleg")) ;;=> 120ms
(require '[pod.retrogradeorbit.bootleg.enlive :as enlive])

(enlive/at "<p>{{here comes foo}}</p>" [:p]
           (enlive/content "foo")) ;;=> 16ms
```

These are some possible optimizations:

- Move describe message to top-level form, making it a compile time constant. The id is not necessary in the reply.
- Pre-serialize the describe message to bencode at compile time and simply use `print` + `flush` to write it to stdout.

The above two strategies only seemed to help a little bit.

- Since the describe message contains lots of client side code, all of this code is evaluated on startup which likely contributes to a performance penalty. The user doesn't use all of these macros all the time. Maybe it's possible to find a way to keep the describe message lean and only send macro and function code on demand. 

Maybe we could defer loading of pod namespace code to the `require` of that namespace. This would work for sci, but not for Clojure. Maybe that's an OK trade-off to make, since Clojure startup is usually around 1.5 or more anyway?

**Comment by borkdude** [comment]
Some more ideas here: https://github.com/babashka/babashka.pods/issues/14

**Comment by borkdude** [comment]
Since it's not clear if any of these ideas really significantly speed up things, I'll close this for now, but at least we have it documented somewhere.

**Comment by retrogradeorbit** [comment]
Thanks for going through all this experimentation

**Comment by borkdude** [comment]
Yes, updated in babashka/babashka.pods#14. It turns out there are significant gains to be made if we split things up per namespace on demand. It's just that with the example I was initially using, it still used the client side heavy namespaces, that's why I didn't see much difference there, since that's where the most time went. When only using markdown for example, things are much faster when splitting things up per namespace.

**Comment by borkdude** [comment]
I have implemented a new pod operation to optimize startup time when only some namespaces are used. PR coming.

**Comment by retrogradeorbit** [comment]
load time on linux slashed from 122 msecs to 18 msecs! Thanks heaps! :partying_face:
